/* ===== Fixtures de demonstração — pt-BR, conteúdo plausível ===== */
import { NewsCard, Match, SocialPost, Corte, Venue } from './types';

export const FIXTURE_NEWS: NewsCard[] = [
  {
    id: 'n1',
    tipo: 'confirmado',
    titulo: 'Reforço confirmado: meia chega para assinar contrato até 2028',
    resumo: 'O jogador desembarcou no Rio e realizou exames médicos. Anúncio oficial previsto para esta tarde.',
    fonte: 'Portal Rubro',
    url_origem: '#',
    imagem_url: 'https://img.olympics.com/images/image/private/t_s_16_9_g_auto/t_s_w1460/f_auto/primary/cgfhijqq1mp14l26gudg',
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    destaque: true,
  },
  {
    id: 'n2',
    tipo: 'rumor',
    titulo: 'Atacante europeu na mira: clube faz proposta milionária',
    resumo: 'Segundo apuração da redação, a diretoria apresentou oferta de 12 milhões de euros pelo centroavante.',
    fonte: 'Blog da Torcida MRN',
    url_origem: '#',
    imagem_url: null,
    timestamp: new Date(Date.now() - 5 * 3600000).toISOString(),
    destaque: false,
  },
  {
    id: 'n3',
    tipo: 'oficial',
    titulo: 'Escalação definida para o clássico de quarta-feira',
    resumo: 'Treinador confirmou os 11 titulares em coletiva. Lateral-direito volta após lesão muscular.',
    fonte: 'Assessoria Esportiva Demo',
    url_origem: '#',
    imagem_url: null,
    timestamp: new Date(Date.now() - 8 * 3600000).toISOString(),
    destaque: true,
  },
  {
    id: 'n4',
    tipo: 'opiniao',
    titulo: 'Coluna: Por que o esquema 4-3-3 é a chave para a temporada',
    resumo: 'Análise tática do nosso colunista sobre a evolução do time nos últimos cinco jogos.',
    fonte: 'Coluna FlaVisão',
    url_origem: '#',
    imagem_url: null,
    timestamp: new Date(Date.now() - 12 * 3600000).toISOString(),
    destaque: false,
  },
  {
    id: 'n5',
    tipo: 'meme',
    titulo: 'O gol de bicicleta que a internet não esquece',
    resumo: 'Compilação dos melhores memes da rodada após o golaço no último minuto.',
    fonte: 'Central da Nação',
    url_origem: '#',
    imagem_url: 'https://www.aljazeera.com/wp-content/uploads/2018/03/d0b83ee677ce434793654dc754fd69a1_8.jpeg?fit=1170%2C780&quality=80',
    timestamp: new Date(Date.now() - 18 * 3600000).toISOString(),
    destaque: false,
  },
  {
    id: 'n6',
    tipo: 'ugc',
    titulo: 'Torcedor registra mosaico épico da arquibancada',
    resumo: 'Vídeo feito pela torcida no setor norte viralizou com mais de 500 mil visualizações.',
    fonte: '@NaçãoRN',
    url_origem: '#',
    imagem_url: null,
    timestamp: new Date(Date.now() - 24 * 3600000).toISOString(),
    destaque: false,
  },
];

export const FIXTURE_MATCHES: Match[] = [
  {
    id: 'm1',
    competicao: 'Brasileirão Série A',
    mandante: 'Time Rubro-Negro',
    visitante: 'Rival Carioca FC',
    data_hora: new Date(Date.now() + 2 * 86400000).toISOString(),
    local: 'Estádio Nacional — Rio de Janeiro',
    status: 'agendado',
    placar_mandante: null,
    placar_visitante: null,
  },
  {
    id: 'm2',
    competicao: 'Copa Libertadores',
    mandante: 'Clube Andino',
    visitante: 'Time Rubro-Negro',
    data_hora: new Date(Date.now() + 7 * 86400000).toISOString(),
    local: 'Estádio Monumental — Buenos Aires',
    status: 'agendado',
    placar_mandante: null,
    placar_visitante: null,
  },
];

export const FIXTURE_SOCIAL: SocialPost[] = [
  {
    id: 's1',
    plataforma: 'twitter',
    autor: 'Fábio Nação',
    handle: '@fabionacao',
    texto: 'QUE JOGO! Terceira vitória seguida, o time tá voando! 🔴⚫ Quem tava no estádio sentiu a energia. Rumo ao título!',
    curtidas: 12400,
    url_post: '#',
    timestamp: new Date(Date.now() - 1 * 3600000).toISOString(),
  },
  {
    id: 's2',
    plataforma: 'instagram',
    autor: 'Raquel Rubro',
    handle: '@raquelrubro',
    texto: 'O mosaico da torcida ontem foi de arrepiar. Cada vez mais orgulho de ser dessa Nação! ❤️🖤',
    curtidas: 8700,
    url_post: '#',
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: 's3',
    plataforma: 'tiktok',
    autor: 'Gol da Galera',
    handle: '@goldagalera',
    texto: 'POV: você tá na arquibancada e sai o gol da virada aos 47 do segundo tempo 😱🔥',
    curtidas: 45200,
    url_post: '#',
    timestamp: new Date(Date.now() - 6 * 3600000).toISOString(),
  },
  {
    id: 's4',
    plataforma: 'youtube',
    autor: 'Canal Bastidores RN',
    handle: '@bastidoresrn',
    texto: 'NOVO VÍDEO: Os bastidores do vestiário após a classificação heroica. Emoção pura!',
    curtidas: 22100,
    url_post: '#',
    timestamp: new Date(Date.now() - 10 * 3600000).toISOString(),
  },
  {
    id: 's5',
    plataforma: 'twitter',
    autor: 'Marcos Nação12',
    handle: '@marcos_nacao12',
    texto: 'Análise rápida: com a volta do lateral, o time ganhou outra dinâmica na saída de bola. O professor acertou a mão!',
    curtidas: 3200,
    url_post: '#',
    timestamp: new Date(Date.now() - 14 * 3600000).toISOString(),
  },
];

export const FIXTURE_CORTES: Corte[] = [
  {
    id: 'c1',
    tipo: 'ugc',
    titulo: 'Golaço de falta visto da arquibancada',
    descricao: 'Ângulo da torcida no setor leste — a bola entrou no ângulo e a galera explodiu!',
    midia_url: 'https://www.binghamtonhomepage.com/wp-content/uploads/sites/79/2026/06/6a414705d859d3.43904097.jpeg?w=2560&h=1440&crop=1',
    midia_tipo: 'video',
    autor: '@torcedor_raiz',
    curtidas: 18700,
    timestamp: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: 'c2',
    tipo: 'meme',
    titulo: 'A cara do rival quando saiu o terceiro gol',
    descricao: 'Compilação dos melhores memes da rodada. A internet não perdoa! 😂',
    midia_url: 'https://cdn.abacus.ai/images/7049a692-e500-4db5-a3ad-e9be6d3365ac.png',
    midia_tipo: 'imagem',
    autor: '@memes_da_nacao',
    curtidas: 32400,
    timestamp: new Date(Date.now() - 7 * 3600000).toISOString(),
  },
  {
    id: 'c3',
    tipo: 'ugc',
    titulo: 'Coreografia completa da organizada no clássico',
    descricao: 'Mais de 40 mil torcedores cantando juntos. Vídeo completo da coreografia.',
    midia_url: 'https://snworksceo.imgix.net/ufa/94f1532b-619a-4fba-b80b-c0d6dc891934.sized-1000x1000.jpg?w=800&dpr=2&ar=16%3A9&fit=crop&crop=faces',
    midia_tipo: 'video',
    autor: '@flagrante_rn',
    curtidas: 55100,
    timestamp: new Date(Date.now() - 15 * 3600000).toISOString(),
  },
  {
    id: 'c4',
    tipo: 'meme',
    titulo: 'Narrador perdendo a voz no gol de empate',
    descricao: 'O áudio viralizou nas redes. "GOOOOOOL" que não acabava mais!',
    midia_url: 'https://cdn.abacus.ai/images/f7b96a07-5819-4495-b21b-fb9121c40453.png',
    midia_tipo: 'video',
    autor: '@cortes_futebol',
    curtidas: 41800,
    timestamp: new Date(Date.now() - 22 * 3600000).toISOString(),
  },
];

export const FIXTURE_VENUES: Venue[] = [
  // Rio de Janeiro
  { id: 'v1', nome: 'Bar do Mengão', tipo: 'bar', cidade: 'Rio de Janeiro', endereco: 'Rua Dias Ferreira, 200', bairro: 'Leblon', descricao: 'Telão gigante, chopp gelado e a torcida mais animada da Zona Sul. Transmissão de todos os jogos.' },
  { id: 'v2', nome: 'Embaixada Nação Carioca', tipo: 'embaixada', cidade: 'Rio de Janeiro', endereco: 'Av. Rio Branco, 1500', bairro: 'Centro', descricao: 'Ponto oficial de encontro da torcida organizada no Centro. Eventos pré-jogo toda rodada.' },
  { id: 'v3', nome: 'Loja Manto Sagrado RJ', tipo: 'loja', cidade: 'Rio de Janeiro', endereco: 'Rua Voluntários da Pátria, 88', bairro: 'Botafogo', descricao: 'Camisas, acessórios e artigos personalizados da torcida. Estamparia na hora.' },
  // São Paulo
  { id: 'v4', nome: 'Reduto Rubro-Negro SP', tipo: 'bar', cidade: 'São Paulo', endereco: 'Rua Augusta, 1200', bairro: 'Consolação', descricao: 'O QG da Nação em Sampa. Promoção de chopp em dia de jogo e telão 4K.' },
  { id: 'v5', nome: 'Embaixada Paulista', tipo: 'embaixada', cidade: 'São Paulo', endereco: 'Av. Paulista, 900', bairro: 'Bela Vista', descricao: 'Maior embaixada fora do Rio. Caravanas organizadas para jogos no Maracanã.' },
  // Belo Horizonte
  { id: 'v6', nome: 'Buteco da Nação BH', tipo: 'bar', cidade: 'Belo Horizonte', endereco: 'Rua Pium-í, 340', bairro: 'Funcionários', descricao: 'Comida mineira e futebol na veia. Ponto de encontro clássico da torcida em BH.' },
  { id: 'v7', nome: 'Loja Manto Sagrado BH', tipo: 'loja', cidade: 'Belo Horizonte', endereco: 'Av. Afonso Pena, 2100', bairro: 'Centro', descricao: 'Filial mineira com produtos exclusivos e lançamentos em primeira mão.' },
  // Recife
  { id: 'v8', nome: 'Bar Nação Nordeste', tipo: 'bar', cidade: 'Recife', endereco: 'Rua do Bom Jesus, 55', bairro: 'Recife Antigo', descricao: 'No coração do Recife Antigo, a Nação se reúne com frevo e paixão rubro-negra.' },
  { id: 'v9', nome: 'Embaixada Pernambuco', tipo: 'embaixada', cidade: 'Recife', endereco: 'Av. Boa Viagem, 3200', bairro: 'Boa Viagem', descricao: 'Eventos, sorteios e transmissões com a galera mais apaixonada do Nordeste.' },
  // Salvador
  { id: 'v10', nome: 'Axé Rubro-Negro', tipo: 'bar', cidade: 'Salvador', endereco: 'Largo do Pelourinho, 12', bairro: 'Pelourinho', descricao: 'Samba, axé e futebol: a mistura perfeita na Bahia. Festas pós-jogo épicas.' },
  { id: 'v11', nome: 'Embaixada Bahia', tipo: 'embaixada', cidade: 'Salvador', endereco: 'Av. Tancredo Neves, 800', bairro: 'Caminho das Árvores', descricao: 'A casa da Nação baiana. Inscrições para sócio-torcedor e caravanas.' },
];
